spring.application.name=desafio-anota-ai

aws.endpoint=http://localhost:4566
aws.accessKeyId=LKIAQAAAAAAAAC427EOR
aws.secretKey=QVUTMc24DbuP6gTdu6mi4f2t1IrXDjpVT6oKxNrc
aws.region=us-east-1
aws.sns.topic.catalog.arn=arn:aws:sns:us-east-1:000000000000:catalog-emit